Repository finalhanghae99/BE, pull requests merged in 2023-01, with the labels that each got.

#3 feature : 테스트(리뷰 컨트롤러 추가)
  src/main/java/com/product/application/review/controller/ReviewController.java
Labels: feat

#9 feature : 로그인 API 생성 완료 + JWT 구현 완료.
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/user/controller/UserController.java
  src/main/java/com/product/application/user/dto/LoginRequestDto.java
  src/main/java/com/product/application/user/jwt/JwtUtil.java
  src/main/java/com/product/application/user/jwt/UserRoleEnum.java
  src/main/java/com/product/application/user/service/UserService.java
Labels: feature

#14 feature : 회원가입시 닉네임 중복성 검사.
  src/main/java/com/product/application/user/controller/UserController.java
  src/main/java/com/product/application/user/dto/NicknamecheckRequestDto.java
  src/main/java/com/product/application/user/repository/UserRepository.java
  src/main/java/com/product/application/user/service/UserService.java
Labels: feature

#17 feature : Open API 데이터 DB에 저장
  build.gradle
  src/main/java/com/product/application/campinginfo/entity/Camping.java
  src/main/java/com/product/application/campinginfo/repository/CampingRepository.java
  src/main/java/com/product/application/openapi/controller/ApiController.java
  src/main/java/com/product/application/openapi/service/ApiService.java
Labels: feature

#19 feature : 양도 글 생성 - campingId 제외
  src/main/java/com/product/application/Application.java
  src/main/java/com/product/application/camping/entity/Camping.java
  src/main/java/com/product/application/camping/entity/CampingLike.java
  src/main/java/com/product/application/camping/repository/CampingRepository.java
  src/main/java/com/product/application/openapi/service/ApiService.java
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/ReservationRequestDto.java
  src/main/java/com/product/application/reservation/entity/Reservation.java
  src/main/java/com/product/application/reservation/repository/ReservationRepository.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
  src/main/java/com/product/application/review/entity/Review.java
  src/main/java/com/product/application/user/repository/UserRepository.java
Labels: feature

#23 feature : 리뷰 수정기능 추가
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/entity/Review.java
  src/main/java/com/product/application/review/service/ReviewService.java
Labels: feature

#33 feature : 리뷰 좋아요 API 구현 완료
  src/main/java/com/product/application/camping/repository/CampingRepository.java
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/RequestReservationDto.java
  src/main/java/com/product/application/reservation/entity/Reservation.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
  src/main/java/com/product/application/review/controller/ReviewLikeController.java
  src/main/java/com/product/application/review/dto/ReviewLikeResponseDto.java
  src/main/java/com/product/application/review/entity/Review.java
  src/main/java/com/product/application/review/entity/ReviewLike.java
  src/main/java/com/product/application/review/repository/ReviewLikeRepository.java
  src/main/java/com/product/application/review/service/ReviewLikeService.java
  src/main/java/com/product/application/user/controller/UserController.java
  src/main/java/com/product/application/user/dto/RequestEmailcheckDto.java
  src/main/java/com/product/application/user/dto/RequestLoginDto.java
  src/main/java/com/product/application/user/dto/RequestNicknamecheckDto.java
  src/main/java/com/product/application/user/dto/RequestSignupDto.java
  src/main/java/com/product/application/user/mapper/UserMapper.java
  src/main/java/com/product/application/user/service/UserService.java
Labels: feature

#35 feat: 전체 조회API((특정 캠핑장에 대한 모든 리뷰 반환)
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/dto/ResponseReviewAllDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewListDto.java
  src/main/java/com/product/application/review/dto/ReviewLikeResponseDto.java
  src/main/java/com/product/application/review/entity/ReviewLike.java
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/review/service/ReviewLikeService.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
Labels: feature, refactoring

#37 feat : 리뷰 글 조회 (특정 1개의 리뷰 상세 정보)
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
Labels: feature

#41 예약 양도 글 상세 조회
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/ResponseReservationDto.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
Labels: feature

#40 캠핑장 찜하기
  src/main/java/com/product/application/camping/controller/CampingController.java
  src/main/java/com/product/application/camping/dto/ResponseCampingLikeStateDto.java
  src/main/java/com/product/application/camping/entity/Camping.java
  src/main/java/com/product/application/camping/entity/CampingLike.java
  src/main/java/com/product/application/camping/repository/CampingLikeRepository.java
  src/main/java/com/product/application/camping/repository/CampingRepository.java
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/dto/RequestFindListTenDto.java
  src/main/java/com/product/application/review/dto/ResponseFindListTenDto.java
  src/main/java/com/product/application/review/repository/ReviewRepository.java
  src/main/java/com/product/application/review/service/ReviewService.java
Labels: feature

#45 feature : 캠핑장 정보 상세조회 :: 4개의 String정보를 배열 변환 및 반환
  src/main/java/com/product/application/camping/dto/ResponseFindDetailCampingInfoDto.java
  src/main/java/com/product/application/camping/service/CampingService.java
Labels: refactoring

#49 feat : 리뷰 글 조회(특정캠핑장 리뷰 중 5개 보여주기)
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/repository/ReviewRepository.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
Labels: feature

#47 feature : 리뷰 삭제
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/repository/ReviewLikeRepository.java
  src/main/java/com/product/application/review/service/ReviewService.java
Labels: feature

#51 feat: 리뷰 조회(전체후기글 좋아요순 정렬 )
  src/main/java/com/product/application/camping/repository/CampingRepository.java
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/repository/ReviewRepository.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
Labels: feature

#52 예약 양도 글 신규 6개 조회 (메인 페이지)
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/ResponseReservationDto.java
  src/main/java/com/product/application/reservation/dto/ResponseSearchDto.java
  src/main/java/com/product/application/reservation/mapper/ReservationMapper.java
  src/main/java/com/product/application/reservation/repository/ReservationRepository.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
Labels: feature

#55 feat : 리뷰 글 좋아요 순 반환(6개만)
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewSixDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewSixListDto.java
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/review/repository/ReviewRepository.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
Labels: feature

#57 refactor : CORS 오류 해결
  src/main/java/com/product/application/camping/controller/CampingController.java
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/openapi/controller/ApiController.java
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/controller/ReviewLikeController.java
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/service/ReviewService.java
  src/main/java/com/product/application/user/controller/UserController.java
Labels: refactoring

#65 feat : 마이페이지 나의 리뷰 확인 + 개인정보 수정
  src/main/java/com/product/application/review/repository/ReviewRepository.java
  src/main/java/com/product/application/user/controller/UserInformationController.java
  src/main/java/com/product/application/user/dto/RequestUserInfoDto.java
  src/main/java/com/product/application/user/entity/Users.java
  src/main/java/com/product/application/user/service/UserInformationService.java
Labels: feature

#66 feature : 리뷰 이미지 업로드, 조회, 수정, 삭제
  .gitignore
  build.gradle
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/reservation/dto/RequestReservationDto.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/dto/RequestReviewWriteDto.java
  src/main/java/com/product/application/review/dto/ResponseDetailCampingInfoReviewDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewListDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/entity/Review.java
  src/main/java/com/product/application/review/service/ReviewService.java
  src/main/java/com/product/application/s3/Img.java
  src/main/java/com/product/application/s3/ImgRepository.java
  src/main/java/com/product/application/s3/S3Config.java
  src/main/resources/application.properties
Labels: feature

#68 feature :리뷰 이미지 조회
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/review/dto/ResponseDetailCampingInfoReviewDto.java
  src/main/java/com/product/application/s3/Img.java
Labels: feature

#70 feature :리뷰 이미지 조회 추가
  src/main/java/com/product/application/review/dto/ResponseReviewListDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
  src/main/java/com/product/application/user/service/UserInformationService.java
Labels: feature

#75 refactor: 리뷰 조회 수정
  src/main/java/com/product/application/openapi/controller/ApiController.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/dto/ResponseDetailCampingInfoReviewDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewListDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewSixDto.java
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/s3/Img.java
Labels: refactoring

#73 예약 양도 글 생성(campingname 삭제 리팩토링)
  src/main/java/com/product/application/reservation/dto/RequestReservationDto.java
Labels: feature

#77 refactor: 리뷰 조회 수정2
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
Labels: refactoring

#79 refactoring : 예약 양도 글 리펙토링
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/RequestReservationDto.java
  src/main/java/com/product/application/reservation/repository/ReservationRepository.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
Labels: refactoring

#81 refactor: 코드 리펙토링(조회 API 수정)
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/review/dto/ResponseReviewListDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewSixDto.java
  src/main/java/com/product/application/review/mapper/ReviewMapper.java
  src/main/java/com/product/application/user/service/UserService.java
Labels: refactoring

#84 refactor : 캠핑장 전체조회, 상세조회 API 수정
  src/main/java/com/product/application/camping/controller/CampingController.java
  src/main/java/com/product/application/camping/dto/ResponseFindDetailCampingInfoDto.java
  src/main/java/com/product/application/camping/dto/ResponseOneCampingInfo.java
  src/main/java/com/product/application/camping/entity/Camping.java
  src/main/java/com/product/application/camping/mapper/CampingMapper.java
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/review/service/ReviewService.java
  src/main/java/com/product/application/user/dto/RequestSignupDto.java
  src/main/java/com/product/application/user/mapper/UserMapper.java
Labels: refactoring

#85 예약 양도 글 수정, review img 파일분리
  src/main/java/com/product/application/camping/service/CampingService.java
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/RequestSearchDto.java
  src/main/java/com/product/application/reservation/dto/ResponseReservationDto.java
  src/main/java/com/product/application/reservation/dto/ResponseSearchDto.java
  src/main/java/com/product/application/reservation/entity/Reservation.java
  src/main/java/com/product/application/reservation/mapper/ReservationMapper.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/dto/RequestReviewWriteDto.java
  src/main/java/com/product/application/review/entity/Review.java
  src/main/java/com/product/application/review/service/ReviewLookUpService.java
  src/main/java/com/product/application/review/service/ReviewService.java
  src/main/java/com/product/application/s3/config/S3Config.java
  src/main/java/com/product/application/s3/entity/Img.java
  src/main/java/com/product/application/s3/repository/ImgRepository.java
  src/main/java/com/product/application/s3/service/S3UploadService.java
  src/main/java/com/product/application/user/service/UserInformationService.java
Labels: refactoring

#88 refactor : 리뷰 작성 API 수정
  src/main/java/com/product/application/review/service/ReviewService.java
Labels: refactoring

#90 feature : 채팅 테스트
  build.gradle
  src/main/java/com/product/application/chat/config/ChatConfig.java
  src/main/java/com/product/application/chat/controller/ChatRoomController.java
  src/main/java/com/product/application/chat/controller/MessageController.java
  src/main/java/com/product/application/chat/entity/ChatMessage.java
  src/main/java/com/product/application/chat/entity/ChatRoom.java
  src/main/java/com/product/application/chat/service/ChatService.java
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
  src/main/resources/application.properties
Labels: feature

#91 refactor : 마이페이지 내가 작성한 리뷰 조회 API 수정
  src/main/java/com/product/application/camping/controller/CampingController.java
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/review/controller/ReviewController.java
  src/main/java/com/product/application/review/controller/ReviewLikeController.java
  src/main/java/com/product/application/review/controller/ReviewLookUpController.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneDto.java
  src/main/java/com/product/application/review/dto/ResponseReviewOneListDto.java
  src/main/java/com/product/application/user/controller/UserController.java
  src/main/java/com/product/application/user/controller/UserInformationController.java
  src/main/java/com/product/application/user/mapper/UserMapper.java
  src/main/java/com/product/application/user/service/UserInformationService.java
Labels: refactoring

#94 feat + refactor: 메인페이지 유저 닉네임 반환 API + 유저 정보 변경
  src/main/java/com/product/application/openapi/controller/ApiController.java
  src/main/java/com/product/application/user/controller/UserController.java
  src/main/java/com/product/application/user/dto/ResponseUserNicknameDto.java
  src/main/java/com/product/application/user/service/UserInformationService.java
  src/main/java/com/product/application/user/service/UserService.java
Labels: feature, refactoring

#96 feat: 마이페이지 내가 작성한 양도글 조회
  src/main/java/com/product/application/openapi/controller/ApiController.java
  src/main/java/com/product/application/reservation/repository/ReservationRepository.java
  src/main/java/com/product/application/user/controller/UserInformationController.java
  src/main/java/com/product/application/user/dto/ResponseUserReservationDto.java
  src/main/java/com/product/application/user/service/UserInformationService.java
Labels: feature

#98 feat: 양도글 상태값 변화 API
  src/main/java/com/product/application/common/exception/ErrorCode.java
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/dto/ResponseReservationDto.java
  src/main/java/com/product/application/reservation/entity/Reservation.java
  src/main/java/com/product/application/reservation/mapper/ReservationMapper.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
  src/main/java/com/product/application/user/service/UserInformationService.java
Labels: feature, refactoring

#101 feat: 양도글 수정 API
  src/main/java/com/product/application/reservation/controller/ReservationController.java
  src/main/java/com/product/application/reservation/entity/Reservation.java
  src/main/java/com/product/application/reservation/service/ReservationService.java
  src/main/java/com/product/application/review/service/ReviewLikeService.java
Labels: feature

#104 Feature/#92 채팅 구현
  src/main/java/com/product/application/chatting/config/ChatConfig.java
  src/main/java/com/product/application/chatting/controller/ChatMessageController.java
  src/main/java/com/product/application/chatting/controller/ChatRoomController.java
  src/main/java/com/product/application/chatting/dto/RequestMessageDto.java
  src/main/java/com/product/application/chatting/dto/ResponseChatListDto.java
  src/main/java/com/product/application/chatting/dto/ResponseChatMessageDto.java
  src/main/java/com/product/application/chatting/dto/ResponseChatNicknameDto.java
  src/main/java/com/product/application/chatting/dto/ResponseChatReservationDto.java
  src/main/java/com/product/application/chatting/dto/ResponseChattingDto.java
  src/main/java/com/product/application/chatting/dto/ResponseNicknameDto.java
  src/main/java/com/product/application/chatting/entity/ChatMessage.java
  src/main/java/com/product/application/chatting/entity/ChatRoom.java
  src/main/java/com/product/application/chatting/entity/MessageType.java
  src/main/java/com/product/application/chatting/mapper/ChattingMapper.java
  src/main/java/com/product/application/chatting/repository/ChatMessageRepository.java
  src/main/java/com/product/application/chatting/repository/ChatRoomRepository.java
  src/main/java/com/product/application/chatting/service/ChatService.java
  src/main/java/com/product/application/common/TimeStampedChat.java
  src/main/java/com/product/application/user/controller/UserInformationController.java
Labels: feature

#103 feat: rds연결 완료 - 현재 서버에서 돌아가는 버전.(시큐리티 작업 전 최종)
  .gitignore
  build.gradle
  src/main/java/com/product/application/review/entity/Review.java
  src/main/java/com/product/application/review/repository/ReviewRepository.java
  src/main/resources/application.properties
Labels: feature

#109 refactor: DB 연결 오류 수정 완료
  src/main/java/com/product/application/security/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: refactoring

#110 Feature/#108
  src/main/java/com/product/application/chat/config/ChatConfig.java
  src/main/java/com/product/application/chat/controller/ChatRoomController.java
  src/main/java/com/product/application/chat/controller/MessageController.java
  src/main/java/com/product/application/chat/entity/ChatMessage.java
  src/main/java/com/product/application/chat/entity/ChatRoom.java
  src/main/java/com/product/application/chat/service/ChatService.java
  src/main/java/com/product/application/chatting/config/ChatConfig.java
  src/main/java/com/product/application/chatting/config/StompHandler.java
  src/main/java/com/product/application/chatting/controller/ChatMessageController.java
  src/main/java/com/product/application/chatting/controller/ChatRoomController.java
  src/main/java/com/product/application/chatting/dto/RequestMessageDto.java
  src/main/java/com/product/application/chatting/entity/ChatMessage.java
  src/main/java/com/product/application/chatting/mapper/ChattingMapper.java
  src/main/java/com/product/application/chatting/repository/ChatMessageRepository.java
  src/main/java/com/product/application/chatting/service/ChatService.java
  src/main/java/com/product/application/reservation/dto/ResponseReservationDto.java
  src/main/java/com/product/application/user/entity/Users.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: refactoring

#112 refactoring : 채팅방 생성 유무
  src/main/java/com/product/application/chatting/controller/ChatRoomController.java
  src/main/java/com/product/application/chatting/repository/ChatRoomRepository.java
  src/main/java/com/product/application/chatting/service/ChatService.java
Labels: refactoring
